services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - jenkins_net

  jenkins:
    build: .
    image: helium-jenkins-controller:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Kyiv
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net

volumes:
  caddy_data:
  caddy_config:
  jenkins_home:

networks:
  jenkins_net: